name: Bug Report
description: File a bug report
title: "A concise title"
labels: ["bug", "awaiting triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: actual
    attributes:
      label: What happened?
      description: Describe the behaviour you observed.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: What did you expect to happen?
      description: Describe how VelocityAutoReconnect should have behaved.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output and, if applicable, censor any personal information of players such as IPs. This will be automatically formatted into code, so no need for backticks.
      render: shell
    validations:
      required: true
  - type: textarea
    id: config
    attributes:
      label: velocityautoreconnect.conf
      description: Please copy and paste your config file. This will be automatically formatted into code, so no need for backticks.
      render: shell
    validations:
      required: true
  - type: textarea
    id: velocityconfig
    attributes:
      label: Velocity Configuration
      description: Please copy and paste your config file. This will be automatically formatted into code, so no need for backticks.
      render: shell
    validations:
      required: true
  - type: textarea
    id: plugins
    attributes:
      label: Velocity Plugins
      description: Please list all other Velocity plugins you are running.
      render: shell
    validations:
      required: true
  - type: checkboxes
    id: requirements_that_keep_me_sane
    attributes:
      label: I am sure that ...
      options:
        - label: I have actually read the documentation and that the error is not caused by my configuration.
          required: true
        - label: I am using the latest version of VelocityAutoReconnect.
          required: true
        - label: I have filled out every required field in this form (including the title field).
          required: true
        - label: I am not using an unsupported Velocity configuration (e.g. running hacky plugins that manipulate packets, such as ones dependent on Protocolize)
          required: true
